### ISSUE TITLE
City of Sebastopol Public Water Connections

### ISSUE THREAD

**Issue by robertopennington** [andyrich/gfs_scwa#12] opened 2022-03-23 23:46 UTC
It appears that City of Sebastopol Connection data was not done correctly.  There are many parcels on Hutchins Lane and elsewhere that are outside of city limits but identified by the City as having a connection.

I'm not sure what the issue is, the R code appears to use data that Shelly had "cleaned".   

Exploring the data, I suggest using a method similar to VOMWD, where we DO NOT assume that every parcel within the City of Sebastopol is connected.

Be careful not to override the connection status for other PWS in SRP

**Comment by robertopennington** [comment] 2022-03-24 18:56
We have this data,  did you find it?

**Comment by andyrich** [comment] 2022-03-24 20:36
Use VOMWD process for sebastopol.

**Comment by andyrich** [comment] 2022-03-28 22:29
duplicate of #13

**Comment by robertopennington** [comment] 2022-03-29 16:32
I don't think this is an exact duplicate of the Penngrove and Petaluma area because for Petaluma Valley the database was starting from scratch.  For SRP the code should be updating the existing database from the previous GUIDE program.  I'm not sure how this impacts the code exactly, but it is probably important.   Note, the Raftellis and previous GUIDE assumed all parcels within City of Seb were connected.  

The other complicating factor is that there are a few mutual water companies that have overlapping service areas with Seb.  Parcels within the mutual water company service areas should be assumed to be connected.  Identical logic was used in VOTWD.

**Comment by andyrich** [comment] 2022-03-29 22:55
I suggest that because this is such a small area that we use the modified values instead of changing the code. The Santa Rosa part of the database seems much more complicated and prone to errors as I don't know all of the details of that database construction.

**Comment by robertopennington** [comment] 2022-03-30 05:08
I'm still a little fuzzy on the WSA_Remove field used in Pet.  I think for Sebastopol, code similar to below might work:
systems_explicit_data <- c("SEBASTOPOL, CITY OF")
### set all parcels in sebastopol to Public_Water_Connection="No"
pson <- pson %>% 
  mutate(Public_Water_Connection = ifelse(
      ! CA_DrinkingWater_SvcArea_Name %in% systems_explicit_data 
      "No", Public_Water_Connection   ))  # Sets Seb parcels to "No", does not override connection status in other PWS
### then use explicit connection data
pson <- pson %>% 
  mutate(
    Public_Water_Connection = 
      ifelse(APN %in% connections_shelly$APN, "Yes", Public_Water_Connection ),  ### This would effectively only add "Yes", and would not convert any "Yes" to "No" in other PWS areas.
    Public_Water_Connection_Modified = NA,
    Water_Source_Comment = NA
    )

**Comment by andyrich** [comment] 2022-03-30 15:56
I'm going to make these changes today. Before I do, here are how affected PWS systems look before we implement the changes
![PETALUMA, CITY OF_parcels_w_gw](https://user-images.githubusercontent.com/16653125/160878401-88883bfe-fc5e-4e1e-9565-95454e75c0e8.png)
![SEBASTOPOL, CITY OF_parcels_w_gw](https://user-images.githubusercontent.com/16653125/160878410-65361f7a-8b5f-43a6-bb40-46c57d4f0bf1.png)
![WINDSOR, TOWN OF_parcels_w_gw](https://user-images.githubusercontent.com/16653125/160878415-cfb4f71b-4bc2-431a-a199-77be4c805c55.png)
![SRP_parcels_w_gw](https://user-images.githubusercontent.com/16653125/160878423-2c38e726-1bde-434f-91c0-f662ea802b58.png)
![SON_parcels_w_gw](https://user-images.githubusercontent.com/16653125/160878426-d0cc79e1-ff5b-4c1c-9639-d9c561a1481e.png)
![PET_parcels_w_gw](https://user-images.githubusercontent.com/16653125/160878428-09e3d293-b0f0-4813-acf7-57955874a967.png)
![PENNGROVE WATER COMPANY (PUC)_parcels_w_gw](https://user-images.githubusercontent.com/16653125/160878431-a65473c5-396a-46e3-a0b1-fdeb187ee6d5.png)
:

**Comment by andyrich** [comment] 2022-03-30 22:14
# these are the updated connection maps

![PENNGROVE WATER COMPANY (PUC)_parcels_w_gw](https://user-images.githubusercontent.com/16653125/160939180-8beb0075-fc0d-435a-bfbe-85e1214dda8f.png)
![PET_parcels_w_gw](https://user-images.githubusercontent.com/16653125/160939182-e3b9b6e1-f32f-49fa-bec7-ef010ea0b470.png)
![PETALUMA, CITY OF_parcels_w_gw](https://user-images.githubusercontent.com/16653125/160939184-4e2e3437-6cec-45b9-a1de-60cc790549c1.png)
![SEBASTOPOL, CITY OF_parcels_w_gw](https://user-images.githubusercontent.com/16653125/160939188-293143fa-1600-42a4-8bc9-468054ca0cae.png)
![SON_parcels_w_gw](https://user-images.githubusercontent.com/16653125/160939191-4cebdb92-8922-4a31-9014-c4d32019aa44.png)
![SRP_parcels_w_gw](https://user-images.githubusercontent.com/16653125/160939192-76e1fde6-d1a5-4c30-9dc2-f22829ac5e52.png)
![WINDSOR, TOWN OF_parcels_w_gw](https://user-images.githubusercontent.com/16653125/160939195-572c3d8e-a272-419e-8af8-b2b20ccfb09c.png)

**Comment by robertopennington** [comment] 2022-03-30 22:57
Northern end of Petaluma Valley seems to have a bunch of parcels listed as "Yes" 

![image](https://user-images.githubusercontent.com/7247088/160944340-5d952106-7793-4a8b-bb4f-aa8e57a76ad0.png)

**Comment by andyrich** [comment] 2022-03-30 23:42
Those parcels are in the cotati water service area:

![image](https://user-images.githubusercontent.com/16653125/160948414-fde5e889-5e97-4c13-8fef-21e4a2cf31dc.png)

**Comment by andyrich** [comment] 2022-03-30 23:46
SHould I remove both City of Cotati from Santa Rosa and Petaluma analyses?

**Comment by andyrich** [comment] 2022-03-31 02:16
**comment from above:**

![image](https://user-images.githubusercontent.com/16653125/160962037-16379263-2df1-4361-b446-09219709871d.png)


this code will not have any effect, and is already being done with current approach that removes sebastopol for PWS service areas. The list of PWS service names are shown below (printed on line 292, just below where the wsa_key is produced. As you can see, sebastopol is not listed. (additionally your code would set all parcels that do not have sebastopol as their PWS to 'NO' due to the '!' sign, which negates True to False and vice versa) Therefore your filter will not set parcels with that PWS name because there are none that match "SEBASTOPOL":

# because we can't find solution, i'm going to close this problem as the number of parcels is too small to be spending more time on this.

 [1] NA
  [2] "BELMONT TERRACE MUTUAL WATER COMPANY"
  [3] "SANTA ROSA, CITY OF"
  [4] "SANTA ROSA, CITY OF; FRITSCH INDUSTRIAL PARK"
  [5] "LA CANTERA RACQUET CLUB; SANTA ROSA, CITY OF"
  [6] "BRANGER MUTUAL WATER COMPANY, INC.; SANTA ROSA, CITY OF"
  [7] "GRAY WATER SYSTEM"
  [8] "COTATI, CITY OF"
  [9] "COTATI, CITY OF; WASHOE HOUSE"
 [10] "HAPPY ACRES MUTUAL BENEFIT WATER SYSTEM"
 [11] "SANTA ROSA, CITY OF; LEISURE MOBILE HOME PARK"
 [12] "NORTHWEST PREP"
 [13] "NORTHWEST PREP; SANTA ROSA, CITY OF"
 [14] "WRIGHT ELEMENTARY SCHOOL"
 [15] "HAWKINS WATER CO-CAL WATER SERVICE (PUC); SANTA ROSA, CITY OF"
 [16] "MICHAEL LUCAS WATER SYSTEM; SANTA ROSA, CITY OF"
 [17] "WRIGHT ELEMENTARY SCHOOL; SANTA ROSA, CITY OF"
 [18] "CALIFORNIA-AMERICAN LARKFIELD (PUC)"
 [19] "JAMES COURT WATER SYSTEM; SANTA ROSA, CITY OF"
 [20] "WAYSIDE GARDENS MOBILE HOME PARK; SANTA ROSA, CITY OF"
 [21] "THE KENWOOD RANCH; WAYSIDE GARDENS MOBILE HOME PARK; SANTA ROSA, CITY OF"
 [22] "SUNSET PARK COMMUNITY; SANTA ROSA, CITY OF"
 [23] "THE KENWOOD RANCH; SANTA ROSA, CITY OF"
 [24] "ROHNERT PARK, CITY OF"
 [25] "ROBIN WAY WATER SYSTEM; SANTA ROSA, CITY OF"
 [26] "EL CRYSTAL MOBILE HOME PARK; SANTA ROSA, CITY OF"
 [27] "NORTH STAR MOBILE HOME PARK; SANTA ROSA, CITY OF"
 [28] "DELORES LANE WATER SYSTEM; SANTA ROSA, CITY OF; SANTA ROSA MOBILE ESTATES"
 [29] "SANTA ROSA, CITY OF; SANTA ROSA MOBILE ESTATES"
 [30] "STRIPE N SEAL"
 [31] "JEHOVAH S WITNESSES HALL"
 [32] "EL PORTAL MOBILE ESTATES; SANTA ROSA, CITY OF"
 [33] "DELORES LANE WATER SYSTEM; SANTA ROSA, CITY OF"
 [34] "MOUNTAIN VIEW MOBILE ESTATES, LLC; SANTA ROSA, CITY OF"
 [35] "STRIPE N SEAL; SANTA ROSA, CITY OF"
 [36] "SANTA ROSA, CITY OF; PLAZA MOBILE HOME PARK"
 [37] "MOORLAND AVENUE APARTMENTS; SANTA ROSA, CITY OF"
 [38] "WESTERN MOBILE HOME PARK; SANTA ROSA, CITY OF"
 [39] "FRIEDMAN BROTHERS HARDWARE; SANTA ROSA, CITY OF"
 [40] "EL CRYSTAL MOBILE HOME PARK; NORTH STAR MOBILE HOME PARK; SANTA ROSA, CITY OF"
 [41] "SANTA ROSA LIQUOR AND DELI; SANTA ROSA, CITY OF"
 [42] "WESTERN MOBILE HOME PARK; SANTA ROSA LIQUOR AND DELI; SANTA ROSA, CITY OF"
 [43] "SONOMA MOUNTAIN COUNTY WATER DISTRICT"
 [44] "ROHNERT PARK, CITY OF; COTATI, CITY OF"
 [45] "COTATI, CITY OF; NEVES FAMILY TRUST WATER SYSTEM"
 [46] "COTATI, CITY OF; MADRONE MUTUAL WATER COMPANY"
 [47] "CANON MANOR WATER SYSTEM"
 [48] "ROHNERT PARK, CITY OF; SONOMA STATE UNIVERSITY"
 [49] "SONOMA STATE UNIVERSITY"
 [50] "BRANGER MUTUAL WATER COMPANY, INC."
 [51] "HOLLAND HEIGHTS MUTUAL WATER COMPANY; SANTA ROSA, CITY OF"
 [52] "HOLLAND HEIGHTS MUTUAL WATER COMPANY"
 [53] "ROHNERT PARK, CITY OF; CANON MANOR WATER SYSTEM"
 [54] "HOLLAND HEIGHTS MUTUAL WATER COMPANY; BRANGER MUTUAL WATER COMPANY, INC.; SANTA ROSA, CITY OF"
 [55] "LA CREMA WINERY"
 [56] "MARTINELLI RANCH"
 [57] "SONOMA CUTRER"
 [58] "SARALEE 3575 SLUSSER ROAD"
 [59] "SONOMA CUTRER; SARALEE 3575 SLUSSER ROAD"
 [60] "SANTA ROSA, CITY OF; CLOVERLEAF RANCH SUMMER CAMP; PARADISE RIDGE WINERY"
 [61] "SANTA ROSA, CITY OF; CLOVERLEAF RANCH SUMMER CAMP"
 [62] "PARADISE RIDGE WINERY"
 [63] "COLONIAL PARK; MOBILE HOME ESTATES"
 [64] "CALIFORNIA-AMERICAN LARKFIELD (PUC); SUTTER SANTA ROSA REGIONAL HOSPITAL"
 [65] "SANTA ROSA, CITY OF; PARADISE RIDGE WINERY"
 [66] "OLIVET ELEMENTARY SCHOOL"
 [67] "CLOVERLEAF RANCH SUMMER CAMP; PARADISE RIDGE WINERY"
 [68] "MARK WEST NEIGHBORHOOD CHURCH"
 [69] "CALIFORNIA-AMERICAN LARKFIELD (PUC); PARADISE RIDGE WINERY"
 [70] "CALIFORNIA-AMERICAN LARKFIELD (PUC); KENDALL-JACKSON WINE CENTER"
 [71] "SUNCE WINERY"
 [72] "HOOK & LADDER VINEYARDS AND WINERY"
 [73] "BOISSET - DE LOACH WINERY"
 [74] "COLONIAL PARK"
 [75] "KENDALL-JACKSON WINE CENTER"
 [76] "MOBILE HOME ESTATES"
 [77] "HUMANE SOCIETY OF SONOMA COUNTY"
 [78] "HESSEL CHURCH"
 [79] "GRAVENSTEIN SCHOOL DISTRICT-GRAVENSTEIN"
 [80] "BALLETTO VINEYARDS"
 [81] "PACK JACK BAR-B-QUE/WITHERS WATER"
 [82] "BRICOLEUR VINEYARDS"
 [83] "FIRCREST MUTUAL WATER COMPANY"
 [84] "SONOMA WINE SHOP"
 [85] "WENDELL LANE MUTUAL WATER COMPANY"
 [86] "COPAIN WINE CELLARS"
 [87] "VINO FARMS, INC. - PRESTON RANCH"
 [88] "RODNEY STRONG VINEYARDS"
 [89] "J VINEYARDS & WINERY; RODNEY STRONG VINEYARDS"
 [90] "KELLY MUTUAL WATER COMPANY"
 [91] "J VINEYARDS & WINERY"
 [92] "STONEGATE MOBILE HOME PARK"
 [93] "KENDALL-JACKSON WINE CENTER; STONEGATE MOBILE HOME PARK"
 [94] "KELLY MUTUAL WATER COMPANY; SONOMA WEST HOLDINGS INDUSTRIAL PARK"
 [95] "MIDGLEY'S COUNTRY FLEA MARKET"
 [96] "MOUNT WESKE ESTATES MUTUAL WATER COMPANY"
 [97] "CHALK HILL WINERY"
 [98] "ATHENA TERRACE MUTUAL WATER COMPANY"
 [99] "MERRIAM WINERY"
[100] "CENTRO CHRISTIANO EVANGELISTICO CHURCH; SANTA ROSA, CITY OF"
[101] "APERTURE CELLARS"
[102] "ROSELAND MOBILE HOME PARK; SANTA ROSA, CITY OF"
[103] "FOG CREST WINERY"
[104] "WILLOWSIDE MUTUAL WATER COMPANY"
[105] "WILLOWSIDE MUTUAL WATER COMPANY; SANTA ROSA GOLF & COUNTRY CLUB"
[106] "CAMPOBELLO"
[107] "LYNMAR WINERY"
[108] "PARK ROYAL MUTUAL WATER COMPANY"
[109] "SANTA ROSA GOLF & COUNTRY CLUB"
[110] "WILLOWSIDE SCHOOL"
[111] "SUMMERFIELD WALDORF SCHOOL"
[112] "SPIDER WEB RANCH"
[113] "BELLEVUE UNION SCH DIST-BELLEVUE SCHOOL"
[114] "MICHAEL ELLIS SCHOOL FOR DOG TRAINERS"
[115] "SANTA ROSA, CITY OF; UNITED RENTALS"
[116] "OAK GROVE SCHOOL DISTRICT OFFICE; WILLOWSIDE SCHOOL"
[117] "SAINTS PETER & PAUL RUSSIAN CHURCH"
[118] "CASA DEL MAR"
[119] "EVERGREEN MOBILE ESTATES"
[120] "SHAMROCK MOBILE HOME PARK"
[121] "SANTA ROSA, CITY OF; JOURNEY'S END MOBILE HOME PARK"

**Closed by andyrich** 2022-03-31 02:16 UTC
