### ISSUE TITLE
Petaluma Public Water Connection

### ISSUE THREAD

**Issue by robertopennington** [andyrich/gfs_scwa#14] opened 2022-03-24 00:01 UTC
There is a residential area northwest of Casa Grande Rd and southwest of Hidden Valley Dr. within the City of Petaluma, where many parcels are identified as NOT connected.  Oddly, they have a residential groundwater use of 0.0.  I don't know what is going on, but these parcels should be identified as having a public water connection.

Note, similar to Rohnert Park and City of Sonoma, all parcels within Petaluma are assumed to be connected.

**Comment by andyrich** [comment] 2022-03-28 22:28
merge with issue #13

**Comment by andyrich** [comment] 2022-03-28 22:28
duplicate of #13

**Closed** 2022-03-29 23:10 UTC
